name: Setup Node.js & pnpm
description: Checkout, install pnpm/Node.js, install dependencies, and run PandaCSS codegen

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
    - run: pnpm install --frozen-lockfile
      shell: bash
    - run: pnpm prepare
      shell: bash
