import { NuqsAdapter } from 'nuqs/adapters/next/app';

import { SystemMessage } from '@/components/blocks/SystemMessage';
import { JotaiProvider } from '@/components/providers/JotaiProvider';

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <JotaiProvider>
          <NuqsAdapter>
            <SystemMessage />
            {children}
          </NuqsAdapter>
        </JotaiProvider>
      </body>
    </html>
  );
}
